import { notFound } from "next/navigation"
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { SovLineChart } from "@/components/sov-line-chart"
import {
  getClient,
  getLatestSov,
  getSovHistory,
} from "@/lib/queries"
import { formatDate, formatPct } from "@/lib/utils"

export const dynamic = "force-dynamic"

// 클라이언트 공개 포털 — /[clientSlug]
// 운영자 데이터(콘텐츠 큐, 매체 어프로치)는 비공개, SOV 추이만 공개
export default async function ClientPortal({
  params,
}: {
  params: Promise<{ clientSlug: string }>
}) {
  const { clientSlug } = await params

  // 시스템 라우트는 catch 안 되도록 (이미 next.js가 처리)
  if (
    clientSlug.startsWith("_") ||
    ["api", "ops", "favicon.ico", "robots.txt", "sitemap.xml"].includes(clientSlug)
  ) {
    notFound()
  }

  const client = await getClient(clientSlug)
  if (!client) notFound()

  const [latest, history] = await Promise.all([
    getLatestSov(clientSlug),
    getSovHistory(clientSlug, 90),
  ])

  return (
    <div className="container mx-auto max-w-4xl px-6 py-12 space-y-8">
      <header className="space-y-3 text-center sm:text-left">
        <p className="text-xs uppercase tracking-wider text-muted-foreground">
          AEO Agency · Client Report
        </p>
        <h1 className="text-3xl font-semibold">{client.brand_name}</h1>
        <p className="text-muted-foreground text-sm">
          타깃 쿼리:{" "}
          <span className="font-mono text-foreground">{client.primary_query ?? "—"}</span>
        </p>
        <p className="text-xs text-muted-foreground">
          온보딩: {formatDate(client.onboarded_at)}
        </p>
      </header>

      <section className="grid gap-4 sm:grid-cols-3">
        <Card>
          <CardHeader>
            <CardDescription>최근 SOV</CardDescription>
            <CardTitle className="text-3xl font-mono">
              {latest ? formatPct(latest.sov_percent) : "—"}
            </CardTitle>
          </CardHeader>
        </Card>
        <Card>
          <CardHeader>
            <CardDescription>답변에 인용된 쿼리</CardDescription>
            <CardTitle className="text-3xl font-mono">
              {latest ? `${latest.cited_us}` : "—"}
            </CardTitle>
          </CardHeader>
        </Card>
        <Card>
          <CardHeader>
            <CardDescription>측정 엔진</CardDescription>
            <CardTitle className="text-base font-mono">
              {latest?.engine ?? "—"}
            </CardTitle>
          </CardHeader>
        </Card>
      </section>

      <section className="space-y-3">
        <h2 className="text-lg font-semibold">SOV 추이 (90일)</h2>
        <Card>
          <CardContent className="pt-6">
            <SovLineChart data={history} target={30} height={300} />
            <p className="text-xs text-muted-foreground mt-2">
              점선: 목표 SOV 30%
            </p>
          </CardContent>
        </Card>
      </section>

      <section>
        <Card>
          <CardHeader>
            <CardTitle>어떻게 측정하나요?</CardTitle>
            <CardDescription>
              Google Gemini 2.5 Flash + google_search grounding 기반
            </CardDescription>
          </CardHeader>
          <CardContent className="text-sm space-y-2 text-muted-foreground">
            <p>
              매일 새벽 03:00(KST) {client.brand_name} 카테고리 관련 쿼리 80개를 Gemini에
              자동 질문 → 답변에 우리 브랜드(또는 URL)가 인용된 비율을 SOV로 측정합니다.
            </p>
            <p>
              SOV가 0%에서 시작해 30%+로 가는 과정 = 자체 사이트 + 외부 매체 + 지식 그래프
              (Wikidata/OSM) 등 다중 채널에 브랜드 정보를 누적하는 과정입니다.
            </p>
          </CardContent>
        </Card>
      </section>

      <footer className="text-xs text-muted-foreground text-center pt-6 border-t">
        Generated by AEO Agency · {new Date().toLocaleDateString("ko-KR")}
      </footer>
    </div>
  )
}

export async function generateStaticParams() {
  return [{ clientSlug: "thebom-tax" }, { clientSlug: "rufruf" }, { clientSlug: "rufruf-mangwon" }, { clientSlug: "thebom" }]
}
